"""implemented_student_table

Revision ID: 3b455b57c41f
Revises: 8b6adfda5293
Create Date: 2022-11-20 11:45:01.700383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b455b57c41f'
down_revision = '8b6adfda5293'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('students', sa.Column('second_name', sa.String(length=50), nullable=False))
    op.add_column('students', sa.Column('pesel', sa.String(length=11), nullable=False))
    op.add_column('students', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('address', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'students', ['pesel'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'address')
    op.drop_column('students', 'phone')
    op.drop_column('students', 'pesel')
    op.drop_column('students', 'second_name')
    op.drop_column('students', 'first_name')
    # ### end Alembic commands ###
